repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.6.0"
  hooks:
  -   id: check-docstring-first
  -   id: check-added-large-files
      args: ['--maxkb=10000']

- repo: local
  hooks:
    - id: qmd-hook
      name: qmd-hook
      entry: python3 qmd_hook.py
      language: python
      pass_filenames: false

- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
  -   id: flake8
      args: ['--ignore=E129,W504']